name: ✨ Feature Request
description: Suggest a new feature or enhancement for the project
title: "Feature :: Feature Title Here"
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: Problem & Solution
      description: What problem does this feature solve? How does it improve the project?
      placeholder: |
        **Problem:** Currently, users cannot...
        **Solution:** This feature would allow users to...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area of the project does this feature relate to?
      options:
        - User Interface / Design
        - Data / Metro Information
        - Navigation / Graph
        - Search Functionality
        - Accessibility
        - Performance
        - Mobile Experience
        - Dark Mode / Theming
        - New Data Field
        - API / Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When a user wants to...
        2. For tourists who need to...
        3. Developers could use this to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? Any specific implementation ideas?
      placeholder: Describe how the feature should work...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought of...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other projects
      placeholder: Drag and drop images here, paste URLs, or describe visually...
    validations:
      required: false

  - type: checkboxes
    id: target-users
    attributes:
      label: Who would benefit from this feature?
      description: Select all that apply
      options:
        - label: Regular commuters
        - label: Tourists and visitors
        - label: Pilgrims visiting the Holy Shrine
        - label: Developers using the dataset
        - label: Mobile users
        - label: People with disabilities
        - label: Non-Persian speakers
        - label: Everyone

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements (Optional)
      description: Any technical considerations or requirements for implementing this feature?
      placeholder: |
        e.g., Would require new data fields in stations.json
        e.g., Might need external API integration
        e.g., Should work offline
    validations:
      required: false

  - type: checkboxes
    id: willingness-to-contribute
    attributes:
      label: Contribution
      description: Would you be interested in helping implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing
        - label: I can provide more information if needed
        - label: I can help with design/mockups
        - label: I can contribute to documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
        - label: I have provided enough detail for others to understand the feature
          required: true
